/*ESTE SCRIPT BORRA TODOS LOS LOTES EXISTENTES EN ALAE*/

DELETE FROM alae_error WHERE 1;
DELETE FROM alae_sample_batch WHERE 1; /*Borramos ALAE SAMPLE BATCH*/
/* DELETE FROM alae_batch_nominal WHERE 1; */
DELETE FROM alae_batch WHERE 1; /*Borramos ALAE BATCH*/

