<div id="logo">
    <img src="<?php echo $this->basePath() ?>/img/alaepeq.png">
</div>
<div id="cerrar">
    [<a href="<?php echo Alae\Service\Helper::getVarsConfig('base_url') . '/index/menu' ?>">regresar al menú</a>]
</div>
<div id="cuerpo">
    <div id="create-analyte" >
        <div style="font-size:0.85em; margin: 25px;">
            <div id="encab">
                <h2>transacciones del sistema</h2>
            </div>
            <h3>Búsqueda por fecha</h3>
            <ul id="errorBox"><?php echo isset($error) ? $error : ""?></ul>
            <form id="audit-form" action="" method="POST">
                <p>
                    <label>Desde:</label>
                    <input class="centro" type="date" name="from" value="">
                    <label>Hasta:</label>
                    <input class="centro" type="date" name="to" value="">
                    <input type="submit" class="btn" value="buscar" />
                </p>
            </form>
            <script>
            $("#audit-form").validate({
                rules: {
                    from: {
                        required: true
                    },
                },
                messages: {
                    from: {
                        required: "<strong>Desde</strong> es requerido"
                    },
                },
                errorLabelContainer: "#errorBox",
                wrapper: "li",
                submitHandler: function(form){
                    form.submit();
                    return true;
                }
            });
            </script>
        </div>
        <div id="datatable" class="<?php echo str_replace(" ", "_", strtolower($user->getFkProfile()->getName())) ?>"></div>
        <script>
            var createNumberIncr = 0;
            var data = <?php echo $data; ?>;
            var filters = <?php echo $header; ?>;
            var columns = <?php echo $columns; ?>;
            var editable = <?php echo $editable; ?>;
            var deleteUrl = basePath + '/analyte/delete';
            var filtersHtml = '<?php echo $filters; ?>';
        </script>
        <script type="text/javascript" src="<?php echo $this->basePath() ?>/js/datatable.js"></script>
    </div>
</div>
