<?php
  ob_start();
?>

<?php
//<page format="432x240" orientation="L" backcolor="#FFFFFF" style="font: arial;">
?>
<page footer="page" format="432x240" backcolor="#FFFFFF" style="font: arial;">

    <?php echo $page; ?>
<page_footer>
    
  </page_footer>
</page>
<?php
$content = ob_get_clean();
// convert to PDF
require_once dirname(__FILE__) . "/html2pdf/html2pdf.class.php";
try
{
    $html2pdf = new HTML2PDF('P', array(432, 240), 'es', true, 'UTF-8', array(0, 0, 0, 0));
    $html2pdf->setDefaultFont('Arial');
    $html2pdf->pdf->SetProtection(array('print'), '', '');
    $html2pdf->writeHTML($content);
    $html2pdf->Output($filename . ".pdf", 'D');
	
}
catch (HTML2PDF_exception $e)
{
    echo $e;
}
exit;
?>