<?php
header('Content-Disposition: attachment; filename="' . $filename . '.xls";');
header('Content-Type: application/vnd.ms-excel;charset=utf-8');
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <h3>INFORMACIÓN GENERAL DE UN ESTUDIO</h3>
        <table width="890" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;margin-top:10px;text-aling:center">
            <tr>
                <td width="200" align="center" height="20" bgcolor="#252525" style="color:#fff;text-aling:justify;">
                    <strong>Código del Estudio</strong>
                </td>
                <td width="71" height="20" bgcolor="#FFFF99" style="border: black 1px solid;">
                    <?php echo $study->getCode(); ?>
                </td>
                <td width="49" height="20"></td>
                <td width="202" align="center" height="20" bgcolor="#252525" style="color:#fff; border: black 1px solid;">
                    <strong>Nº de Analitos</strong>
                </td>
                <td width="71" height="20" bgcolor="#FFFF99" style="border: black 1px solid;">
                    <?php echo $counterAnalyte; ?>
                </td>
                <td width="33" height="20"></td>
                <td width="201" height="20" bgcolor="#252525" style="color:#fff; border: black 1px solid;">
                    <strong>Arbol de Dilución Nº</strong>
                </td>
                <td width="63" height="20" bgcolor="#FFFF99" style="border: black 1px solid;">
                    <?php echo $study->getFkDilutionTree(); ?>
                </td>
            </tr>
        </table>
        <table width="890" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;">
            <tr>
                <td width="200" bgcolor="#FFFFFF"></td>
            </tr>
            <tr>
                <td width="200" bgcolor="#FFFFFF" colspan="3">
                    <table width="279" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;margin-top:10px;text-aling:center">
                        <tr>
                            <td width="108" bgcolor="#FFFFFF" style="color:#fff; border:0;"></td>
                            <td colspan="2" align="center" bgcolor="#252525" style="color:#fff; border: black 1px solid;text-aling:center" >
                                <strong>Analitos</strong>
                            </td>
                        </tr>
                        <tr>
                            <td width="108" bgcolor="#FFFFFF" style="color:#000; border:0;"></td>
                            <td width="56" align="center"  bgcolor="#D8D8D8" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                                <strong>Nombre</strong>
                            </td>
                            <td width="115" align="center"  bgcolor="#D8D8D8" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                                <strong>Abreviatura</strong>
                            </td>
                        </tr>
                        <?php $count = 1; foreach ($analytes as $anaStudy) : ?>
                        <tr>
                            <td width="108" bgcolor="#F1DADA" style="color:#000; border:0;">
                                <?php echo $count; ?>
                            </td>
                            <td width="56" align="center"  bgcolor="#FFFF99" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                                <?php echo $anaStudy->getFkAnalyte()->getName(); ?>
                            </td>
                            <td width="115" align="center"  bgcolor="#FFFF99" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                                <?php echo $anaStudy->getFkAnalyte()->getShortening(); ?>
                            </td>
                        </tr>
                        <?php $count++; endforeach; ?>
                    </table>
                </td>
                <td width="200" bgcolor="#FFFFFF"></td>
                <td width="200" bgcolor="#FFFFFF" colspan="5">
                    <table width="349" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;margin-top:10px;text-aling:center">
                        <tr>
                            <td colspan="4" align="center" bgcolor="#252525" style="color:#fff; border: black 1px solid;text-aling:center;" >
                                <strong>Patrón inteno</strong>
                            </td>
                        </tr>
                        <tr>
                            <td width="89" align="center"  bgcolor="#D8D8D8" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                                <strong>Nombre</strong>
                            </td>
                            <td width="94" align="center"  bgcolor="#D8D8D8" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                                <strong>Abreviatura</strong>
                            </td>
                            <td width="102" align="center"  bgcolor="#D8D8D8" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                                <strong>% Variabilidad</strong>
                            </td>
                            <td width="62" align="center"  bgcolor="#D8D8D8" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                                <strong>Usar</strong>
                            </td>
                        </tr>
                        <?php $count = 1; foreach ($analytes as $anaStudy) : ?>
                        <tr>
                            <td width="89" align="center"  bgcolor="#FFFF99" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                                <?php echo $anaStudy->getFkAnalyteIs()->getName(); ?>
                            </td>
                            <td width="94" align="center"  bgcolor="#FFFF99" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                                <?php echo $anaStudy->getFkAnalyteIs()->getShortening(); ?>
                            </td>
                            <td width="102" align="center"  bgcolor="#FFFF99" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                                <?php echo $anaStudy->getInternalStandard(); ?>
                            </td>
                            <td width="62" align="center"  bgcolor="#FFFF99" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                                <?php echo $anaStudy->getIsUsed() ? "S" : "N"; ?>
                            </td>
                        </tr>
                        <?php $count++; endforeach; ?>
                    </table>
                </td>
            </tr>
            <tr>
                <td width="200" bgcolor="#FFFFFF"></td>
            </tr>
        </table>
        <div class="clear"></div>
        <div class="table-row">
            <p><strong>Concentración Nominal de los Estándares de Calibración</strong></p>
            <table width="600" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;margin-top:10px;text-aling:center">
                <tr>
                    <td align="center" bgcolor="#252525" style="color:#fff; border: black 1px solid;text-aling:center">
                        <strong>Identificación de la muestra</strong>
                    </td>
                    <?php foreach ($analytes as $anaStudy) : ?>
                    <td align="center" bgcolor="#252525" style="color:#fff; border: black 1px solid;text-aling:center">
                        <strong>Conc. <?php echo $anaStudy->getFkAnalyte()->getName(); ?></strong>
                    </td>
                    <?php endforeach; ?>
                </tr>
                <tr>
                    <td align="center" bgcolor="#252525" style="color:#fff; border: black 1px solid;text-aling:center"></td>
                    <?php foreach ($analytes as $anaStudy) : ?>
                    <td align="center" bgcolor="#252525" style="color:#fff; border: black 1px solid;text-aling:center">
                        <strong>(<?php echo $anaStudy->getFkUnit()->getName(); ?>)</strong>
                    </td>
                    <?php endforeach; ?>
                </tr>
                <?php for($i = 0; $i < $anaStudy->getCsNumber(); $i++) : ?>
                <tr>
                    <td width="89" align="center"  bgcolor="#F1DADA" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                        CS<?php echo $i + 1; ?>
                    </td>
                    <?php foreach ($cs_values as $key => $value) : ?>
                    <td width="89" align="center"  bgcolor="#B7CCE3" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                        <?php echo $cs_values[$key][$i]; ?>
                    </td>
                    <?php endforeach; ?>
                </tr>
                <?php endfor; ?>
            </table>
        </div>
        <div class="table-row">
            <p><strong>Concentración Nominal de los Controles de Calidad</strong></p>
            <table width="600" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;margin-top:10px;text-aling:center">
                <tr>
                    <td align="center" bgcolor="#252525" style="color:#fff; border: black 1px solid;text-aling:center">
                        <strong>Identificación de la muestra</strong>
                    </td>
                    <?php foreach ($analytes as $anaStudy) : ?>
                    <td align="center" bgcolor="#252525" style="color:#fff; border: black 1px solid;text-aling:center">
                        <strong>Conc. <?php echo $anaStudy->getFkAnalyte()->getName(); ?></strong>
                    </td>
                    <?php endforeach; ?>
                </tr>
                <tr>
                    <td align="center" bgcolor="#252525" style="color:#fff; border: black 1px solid;text-aling:center"></td>
                    <?php foreach ($analytes as $anaStudy) : ?>
                    <td align="center" bgcolor="#252525" style="color:#fff; border: black 1px solid;text-aling:center">
                        <strong>(<?php echo $anaStudy->getFkUnit()->getName(); ?>)</strong>
                    </td>
                    <?php endforeach; ?>
                </tr>
                <?php for($i = 0; $i < $anaStudy->getQcNumber(); $i++) : ?>
                <tr>
                    <td width="89" align="center"  bgcolor="#F1DADA" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                        QC<?php echo $i + 1; ?>
                    </td>
                    <?php foreach ($qc_values as $key => $value) : ?>
                    <td width="89" align="center"  bgcolor="#B7CCE3" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                        <?php echo $qc_values[$key][$i]; ?>
                    </td>
                    <?php endforeach; ?>
                </tr>
                <?php endfor; ?>
                <tr>
                    <td width="89" align="center"  bgcolor="#F1DADA" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                        LDQC
                    </td>
                    <?php foreach ($analytes as $anaStudy) : ?>
                    <td width="89" align="center"  bgcolor="#B7CCE3" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                        <?php echo $anaStudy->getLdqcValues(); ?>
                    </td>
                    <?php endforeach; ?>
                </tr>
                <tr>
                    <td width="89" align="center"  bgcolor="#F1DADA" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                        HDQC
                    </td>
                    <?php foreach ($analytes as $anaStudy) : ?>
                    <td width="89" align="center"  bgcolor="#B7CCE3" style="color:#000; border: black 1px solid;text-aling:center;font-size:11px;padding:4px">
                        <?php echo $anaStudy->getHdqcValues(); ?>
                    </td>
                    <?php endforeach; ?>
                </tr>
            </table>
        </div>
        <div class="table-row">
            <table width="400" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;margin-top:10px;text-aling:center;">
                <tr>
                    <td  bgcolor="#FFFFFF" style="color:#fff; border:0;"></td>
                </tr>
                <tr>
                    <td align="center" bgcolor="#252525" style="color:#fff; border: black 1px solid;text-aling:center;">
                        Elaboración:
                    </td>
                    <td align="center" bgcolor="#fff" style="text-aling:center;" >
                        (<?php echo $study->getFkUser()->getUsername(); ?>)
                    </td>
                </tr>
                <tr>
                    <td align="center" bgcolor="#252525" style="color:#fff; border: black 1px solid;text-aling:center;">
                        Aprobación:
                    </td>
                    <td align="center" bgcolor="#fff" style="text-aling:center;" >
                        (<?php echo !is_null($study->getFkUserApprove()) ? $study->getFkUserApprove()->getUsername() : "Sin aprobación"; ?>)
                    </td>
                </tr>
                <tr>
                <tr>
                    <td align="center" bgcolor="#fff" style="text-aling:center;" colspan="2">
                        <?php echo date("d.m.Y H:i:s"); ?>
                    </td>
                </tr>
            </table>
        </div>
    </body>
</html>