<nobreak>
<div>

<table border="0" cellspacing="0" cellpadding="0"  style="padding:20px; width:100%;background-color:#fff;text-aling:center; font-size:20px;">
<tr>
<td>
<strong>INFORMACIÓN GENERAL DE UN ESTUDIO</strong>
</td>
</tr>
</table>
    
    <table border="0" cellspacing="0" cellpadding="0" style="padding:20px; width:100%;margin-top:10px;text-aling:center">
        <tr>
            <td align="center" height="20" bgcolor="#252525" style="width:10%;color:#fff;text-aling:justify;border: white 1px solid;">
                <strong>Código del Estudio</strong>
            </td>
            <td align="center" height="20" style="border: black 1px solid;">
                <?php echo $study->getCode(); ?>
            </td>
        </tr>

        <tr>
            <td align="center" height="20" bgcolor="#252525" style="width:10%;color:#fff;text-aling:justify;border: white 1px solid;">
                <strong>Nº de Analitos</strong>
            </td>
            <td   align="center" height="20" style="border: black 1px solid;">
                <?php echo $counterAnalyte; ?>
            </td>
        </tr>

        <tr>
            <td align="center" height="20" bgcolor="#252525" style="width:10%;color:#fff;text-aling:justify;border: white 1px solid;">
                <strong>Arbol de Dilución Nº</strong>
            </td>
            <td   align="center" height="20" style="border: black 1px solid;">
                <?php echo $study->getFkDilutionTree(); ?>
            </td>
        </tr>
    </table>

    <table border="0" cellspacing="0" cellpadding="0" style="padding:20px; width:100%;margin-top:10px;text-aling:center">

        <tr>
            <td  align="center" width ="100" bgcolor="#000000" style="color:#ffffff;border: black 1px solid;font-size:11px;">
                <strong>Analito</strong>
            </td>
            <td colspan="5" bgcolor="#000000"></td>
            <td  align="center" width ="100" bgcolor="#000000" style="color:#ffffff;border: black 1px solid;font-size:11px;">
                <strong>Patrón interno</strong>
            </td>
            <td colspan="5" bgcolor="#000000"></td>
            <td  align="center" width ="100" colspan="2" bgcolor="#000000" style="color:#ffffff;border: black 1px solid;font-size:11px;">
                <strong>% Var IS</strong>
            </td>
        </tr>

        <tr>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Nombre</strong></td>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Abr.</strong></td>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>M. Aceptación</strong></td>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Retención</strong></td>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Min</strong></td>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Max</strong></td>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Nombre</strong></td>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Abr.</strong></td>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>M. Aceptación</strong></td>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Retención</strong></td>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Min</strong></td>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Max</strong></td>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>usar</strong></td>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>% Var IS</strong></td>
        </tr>

        <?php $count = 1; foreach ($analytes as $anaStudy) : ?>
        <tr>
            <td  align="center" width ="100"   style="color:#000000;border: black 1px solid;font-size:11px;">
                <?php echo $anaStudy->getFkAnalyte()->getName(); ?>
            </td>
            <td  align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                <?php echo $anaStudy->getFkAnalyte()->getShortening(); ?>
            </td>
            <td  align="right" width ="100" style="color:#000000;border: black 1px solid;font-size:11px;">
                <?php 
                    echo number_format($anaStudy->getAcceptance(), 2, '.', '');  
                ?>
            </td>
            <td  align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                <?php 
                    echo number_format($anaStudy->getRetention(), 2, '.', ''); 
                ?>
            </td>
            <td  align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                <?php $min = $anaStudy->getRetention() - ($anaStudy->getAcceptance() * $anaStudy->getRetention() / 100);?>
                <?php 
                    echo number_format($min, 2, '.', '');  
                ?>
            </td>
            <td  align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                <?php $max = $anaStudy->getRetention() + ($anaStudy->getAcceptance() * $anaStudy->getRetention() / 100); ?>
                <?php 
                    echo number_format($max, 2, '.', '');  
                ?>
            </td>
            <td  align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                <?php echo $anaStudy->getFkAnalyteIs()->getName(); ?>
            </td>
            <td  align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                <?php echo $anaStudy->getFkAnalyteIs()->getShortening(); ?>
            </td>
            <td  align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                <?php 
                    echo number_format($anaStudy->getAcceptanceIs(), 2, '.', '');  
                ?>
            </td>
            <td  align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                <?php 
                    echo number_format($anaStudy->getRetentionIs(), 2, '.', '');  
                ?>
            </td>
            <td  align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                <?php $min_is = $anaStudy->getRetentionIs() - ($anaStudy->getAcceptanceIs() * $anaStudy->getRetentionIs() / 100); ?>
                <?php 
                    echo number_format($min_is, 2, '.', '');  
                ?>
            </td>
            <td  align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                <?php $max_is = $anaStudy->getRetentionIs() + ($anaStudy->getAcceptanceIs() * $anaStudy->getRetentionIs() / 100); ?>
                <?php 
                    echo number_format($max_is, 2, '.', '');  
                ?>
            </td>
            <td  align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                <?php echo $anaStudy->getIsUsed() ? "S" : "N"; ?>
            </td>
            <td  align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                <?php 
                    echo number_format($anaStudy->getInternalStandard(), 2, '.', '');  
                ?>
            </td>
        </tr>
        <?php $count++; endforeach; ?>
    </table>

    <table border="0" cellspacing="0" cellpadding="0" style="padding:20px; width:100%;margin-top:10px;text-align:center">
        <tr>
            <td align="center" width ="100" colspan="4" bgcolor="#000000" style="color:#ffffff;border: black 1px solid;font-size:11px;">
                <strong>Concentración Nominal de los Estándares de Calibración</strong>
            </td>
        </tr>

        <tr>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Analito</strong></td>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Unidad</strong></td>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Muestra</strong></td>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Concentración nominal</strong></td>
        </tr>
        <?php  foreach ($cs_values as $cs_value) : ?>
            <tr>
                <td align="left" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $cs_value["analyte"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $cs_value["unit"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $cs_value["sample"]; ?></strong>
                </td>
                <td align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong>
                        <?php 
                            echo empty($cs_value["value"]) ? '' : number_format($cs_value["value"], 2, '.', ''); 
                        ?>
                    </strong>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>

    <table border="0" cellspacing="0" cellpadding="0" style="padding:20px; width:100%;margin-top:10px;text-align:center">
        <tr>
            <td align="center" width ="100" colspan="4" bgcolor="#000000" style="color:#ffffff;border: black 1px solid;font-size:11px;">
                <strong>Concentración Nominal de los Controles de Calidad</strong>
            </td>
        </tr>
        <tr>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Analito</strong></td>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Unidad</strong></td>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Muestra</strong></td>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Concentración nominal</strong></td>
        </tr>
        <?php  foreach ($qc_values as $qc_value) : ?>
            <tr>
                <td align="left" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $qc_value["analyte"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $qc_value["unit"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $qc_value["sample"]; ?></strong>
                </td>
                <td align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong>
                        <?php 
                            echo empty($qc_value["value"]) ? '' : number_format($qc_value["value"], 2, '.', ''); 
                        ?>
                    </strong>
                </td>
            </tr>
        <?php endforeach; ?>

        <?php  foreach ($ldqc_values as $ldqc_value) : ?>
            <tr>
                <td align="left" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $ldqc_value["analyte"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $ldqc_value["unit"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $ldqc_value["sample"]; ?></strong>
                </td>
                <td align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong>
                        <?php 
                            echo empty($ldqc_value["value"]) ? '' : number_format($ldqc_value["value"], 2, '.', ''); 
                        ?>
                    </strong>
                </td>
            </tr>
        <?php endforeach; ?>

        <?php  foreach ($hdqc_values as $hdqc_value) : ?>
            <tr>
                <td align="left" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $hdqc_value["analyte"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $hdqc_value["unit"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $hdqc_value["sample"]; ?></strong>
                </td>
                <td align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong>
                        <?php 
                            echo empty($hdqc_value["value"]) ? '' : number_format($hdqc_value["value"], 2, '.', ''); 
                        ?>
                    </strong>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>

    <table border="0" cellspacing="0" cellpadding="0" style="padding:20px; width:100%;margin-top:10px;text-align:center">
        <tr>
            <td   align="left" height=2 bgcolor="#ffffff" style="color:#000000;font-size:11px;padding:10px">&nbsp;</td>
        </tr>
        <tr>
            <td   height=20  height="20" bgcolor="#000000" style="color:#ffffff;font-size:11px;padding:10px">
                <strong>Elaboración</strong>
            </td>
            <td   height=20  height="20"  style="color:#000000;font-size:11px;padding:10px">
                (<?php echo $study->getFkUser()->getUsername(); ?>)
            </td>
        </tr>
        <tr>
            <td   height="20" bgcolor="#000000" style="color:#ffffff;font-size:11px;padding:10px">
                Aprobación:
            </td>
            <td   height=20   style="color:#000000;font-size:11px;padding:10px">
                (<?php echo !is_null($study->getFkUserApprove()) ? $study->getFkUserApprove()->getUsername() : "Sin aprobación"; ?>)
            </td>
        </tr>
        <tr>
            <td align="center" bgcolor="#fff" style="text-align:center;">
                 <?php echo date("d.m.Y H:i:s"); ?>
            </td>
        </tr>
    </table>

</div>
</nobreak>