<?php
header('Content-Disposition: attachment; filename="'. $filename .'.xls";');
header('Content-Type: application/vnd.ms-excel;charset=utf-8');
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
	<div class="table-container">
	    <h3>RESUMEN DE LOTES DE UN ESTUDIO </h3>
	    <table width="900" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;padding: 4px;font-size:11px;">
		<tr>
		    <td width="238" align="left" height="20" bgcolor="#000000" style="border: black 1px solid;color:#97C1DA;padding: 4px">
			Código del estudio:
		    </td>
		    <td width="205" height="20" style="border: black 1px solid;padding: 4px;">
                    <?php echo $batch->getFkStudy()->getCode(); ?>
		    </td>
		    <td width="273" height="20" bgcolor="#000000" style="border: black 1px solid;color:#F1DADA;padding: 4px">
			Analito
		    </td>
		    <td width="174" align="center" height="20" style="border: black 1px solid;">
                        <?php echo $batch->getFkAnalyte()->getName(); ?>
		    </td>
		</tr>
                <tr>
                    <td colspan="4">
                        <table width="900" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;margin-top:10px;font-size:11px;">
                            <tr>
                                <td colspan="3"></td>
                            </tr>
                            <tr>
                                <td colspan="3"></td>
                            </tr>
                            <tr>
                                <td width="238" align="left" height="20" bgcolor="#000000" style="border: black 1px solid;color:#97C1DA;padding:4px;font-size:11px;">
                                    Identificación de la muestra
                                </td>
                                <td width="238" align="left" height="20" bgcolor="#000000" style="border: black 1px solid;color:#97C1DA;padding: 4px">
                                    Evaluación ( Aceptado / Rechazado )
                                </td>
                                <td width="238" align="left" height="20" bgcolor="#000000" style="border: black 1px solid;color:#97C1DA;padding: 4px">
                                    Motivo ( En caso de ser Rechazado )
                                </td>
                            </tr>
                            <?php foreach ($list as $key => $value) : ?>
                            <tr>
                                <td width="238" align="left" height="20" bgcolor="#B7CCE3" style="border: black 1px solid;padding:4px;">
                                    <?php echo $value['sample_name']; ?>
                                </td>
                                <td width="238" align="left" height="20" bgcolor="#B7CCE3" style="border: black 1px solid;padding:4px;">
                                    <?php echo $value['status']; ?>
                                </td>
                                <td width="238" align="left" height="20" bgcolor="#F1DADA" style="border: black 1px solid;padding:4px;">
                                    <?php echo $value['error']; ?>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                            <tr>
                                <td align="right" height="20" colspan="2">
                                    Fecha de la Evaluación:
                                </td>
                                <td  align="left" height="20">
                                    <?php echo $batch->getValidationDate(); ?>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
	    </div>
    </body>
</html>
