<html>
    <head>
        <title>ALAE</title>
        <style type="text/css" media="Screen"> /*\*/@import url("./css/alae.css");/**/ </style>
        <link rel="shortcut icon" href="img/favicon.ico">
    </head>
    <body>
        <div id="principal">
            <div id="cuerpo">
                <div id="central" style="text-align:left; font-size:1.1em;">
                    <hr/>
                    <blockquote>
                        Han solicitado acceso al sistema ALAE, con los siguientes datos: <br>
                        Nombre de usuario: <strong><?php echo $user; ?></strong><br>
                        Correo electrónico: <strong><?php echo $email; ?></strong>
                    </blockquote>
                </div>
            </div>
        </div>
    </body>
</html>