<html>
    <div id="principal">
	<div id="cuerpo">

	    <div id="central">
		<a href="<?php echo $this->url('user', array('action' => 'login')); ?>">
		    <img src="<?php echo $this->basePath() . '/img/alae_logo.png.png' ?>"/>
		</a>
		<?php
		echo $message;
		if ($showForm == true)
		{
		    ?>
    		<div id="login">
    		    <h1>Reinicializar contraseña</h1>
    		    <form method="POST"  id="newpasswordusr" action="<?php echo $this->url('user', array('action' => 'newpassword')); ?>">
    			<table>
    			    <tbody><tr><td>Nombre de usuario:</td>
    				    <td> <?php echo $username ?></td></tr>
    				<tr><td>Nueva Contraseña (*):</td>
    				    <td><input type="password" id="pwd" name="pwd"></td></tr>
    				<tr><td>Confirmar contraseña (*):</td>
    				    <td><input type="password" id="password" name="password">
    				    </td></tr>
    				<tr><td>Correo electrónico:</td>
    				    <td><?php echo $email ?></td></tr>
    				<tr><td>Perfil:</td>
    				    <td><?php echo $perfil ?></td></tr>
    				<tr><td>
    					<p class="peq" style="color:#f00">(*) Requerido</p></td>
    			    <input type="text" id="id" name="id" style="display:none" value="<?php echo $id ?>" >
    			    <td><a href="">
    				    <input type="submit" value="Actualizar usuario" id="enviar"></a>
    			    </td></tr>
    			    </tbody></table>
    		    </form>
    		</div>
		    <?php
		}
		?>
	    </div>
	</div>
	<div id="pie">
	    <p><a href="./help/alaeIndex.pdf" target="blank"><img src="./img/help.png" title="ayuda sobre esta pantalla"></a>
		Ayuda sobre el Sistema</p>
	    <p><a href="./sf/alae001sf.pdf" target="blank"><img src="./img/info.png" title="Especificaciones funcionales"></a>
		ALAE Software. Copyright © Anapharm, 2020.</p>
	</div>
    </div>
</html>



