<?php

namespace DoctrineORMModule\Proxy\__CG__\Alae\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AnalyteStudy extends \Alae\Entity\AnalyteStudy implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'pkAnalyteStudy', 'csNumber', 'qcNumber', 'csValues', 'hdqcValues', 'ldqcValues', 'llqcValues', 'ulqcValues', 'qcValues', 'internalStandard', 'status', 'isUsed', 'updatedAt', 'fkStudy', 'fkAnalyte', 'fkAnalyteIs', 'fkUnit', 'fkUser', 'fkUserApprove', 'retention', 'acceptance', 'retentionIs', 'acceptanceIs', 'associatedAt', 'fkUserAssociated');
        }

        return array('__isInitialized__', 'pkAnalyteStudy', 'csNumber', 'qcNumber', 'csValues', 'hdqcValues', 'ldqcValues', 'llqcValues', 'ulqcValues', 'qcValues', 'internalStandard', 'status', 'isUsed', 'updatedAt', 'fkStudy', 'fkAnalyte', 'fkAnalyteIs', 'fkUnit', 'fkUser', 'fkUserApprove', 'retention', 'acceptance', 'retentionIs', 'acceptanceIs', 'associatedAt', 'fkUserAssociated');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AnalyteStudy $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPkAnalyteStudy()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getPkAnalyteStudy();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPkAnalyteStudy', array());

        return parent::getPkAnalyteStudy();
    }

    /**
     * {@inheritDoc}
     */
    public function setPkAnalyteStudy($pkAnalyteStudy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPkAnalyteStudy', array($pkAnalyteStudy));

        return parent::setPkAnalyteStudy($pkAnalyteStudy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCsNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCsNumber', array());

        return parent::getCsNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setCsNumber($csNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCsNumber', array($csNumber));

        return parent::setCsNumber($csNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getQcNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQcNumber', array());

        return parent::getQcNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setQcNumber($qcNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQcNumber', array($qcNumber));

        return parent::setQcNumber($qcNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getCsValues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCsValues', array());

        return parent::getCsValues();
    }

    /**
     * {@inheritDoc}
     */
    public function setCsValues($csValues)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCsValues', array($csValues));

        return parent::setCsValues($csValues);
    }

    /**
     * {@inheritDoc}
     */
    public function getQcValues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQcValues', array());

        return parent::getQcValues();
    }

    /**
     * {@inheritDoc}
     */
    public function setQcValues($qcValues)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQcValues', array($qcValues));

        return parent::setQcValues($qcValues);
    }

    /**
     * {@inheritDoc}
     */
    public function getInternalStandard()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInternalStandard', array());

        return parent::getInternalStandard();
    }

    /**
     * {@inheritDoc}
     */
    public function setInternalStandard($internalStandard)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInternalStandard', array($internalStandard));

        return parent::setInternalStandard($internalStandard);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsUsed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsUsed', array());

        return parent::getIsUsed();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsUsed($isUsed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsUsed', array($isUsed));

        return parent::setIsUsed($isUsed);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkStudy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkStudy', array());

        return parent::getFkStudy();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkStudy(\Alae\Entity\Study $fkStudy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkStudy', array($fkStudy));

        return parent::setFkStudy($fkStudy);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkAnalyte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkAnalyte', array());

        return parent::getFkAnalyte();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkAnalyte(\Alae\Entity\Analyte $fkAnalyte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkAnalyte', array($fkAnalyte));

        return parent::setFkAnalyte($fkAnalyte);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkAnalyteIs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkAnalyteIs', array());

        return parent::getFkAnalyteIs();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkAnalyteIs(\Alae\Entity\Analyte $fkAnalyteIs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkAnalyteIs', array($fkAnalyteIs));

        return parent::setFkAnalyteIs($fkAnalyteIs);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkUnit', array());

        return parent::getFkUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkUnit(\Alae\Entity\Unit $fkUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkUnit', array($fkUnit));

        return parent::setFkUnit($fkUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkUser', array());

        return parent::getFkUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkUser(\Alae\Entity\User $fkUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkUser', array($fkUser));

        return parent::setFkUser($fkUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkUserApprove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkUserApprove', array());

        return parent::getFkUserApprove();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkUserApprove(\Alae\Entity\User $fkUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkUserApprove', array($fkUser));

        return parent::setFkUserApprove($fkUser);
    }

    /**
     * {@inheritDoc}
     */
    public function setLdqcValues($ldqcValues)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLdqcValues', array($ldqcValues));

        return parent::setLdqcValues($ldqcValues);
    }

    /**
     * {@inheritDoc}
     */
    public function getLdqcValues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLdqcValues', array());

        return parent::getLdqcValues();
    }

    /**
     * {@inheritDoc}
     */
    public function setHdqcValues($hdqcValues)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHdqcValues', array($hdqcValues));

        return parent::setHdqcValues($hdqcValues);
    }

    /**
     * {@inheritDoc}
     */
    public function getHdqcValues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHdqcValues', array());

        return parent::getHdqcValues();
    }

    /**
     * {@inheritDoc}
     */
    public function setLlqcValues($llqcValues)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLlqcValues', array($llqcValues));

        return parent::setLlqcValues($llqcValues);
    }

    /**
     * {@inheritDoc}
     */
    public function getLlqcValues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLlqcValues', array());

        return parent::getLlqcValues();
    }

    /**
     * {@inheritDoc}
     */
    public function setUlqcValues($ulqcValues)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUlqcValues', array($ulqcValues));

        return parent::setUlqcValues($ulqcValues);
    }

    /**
     * {@inheritDoc}
     */
    public function getUlqcValues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUlqcValues', array());

        return parent::getUlqcValues();
    }

    /**
     * {@inheritDoc}
     */
    public function getRetention()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRetention', array());

        return parent::getRetention();
    }

    /**
     * {@inheritDoc}
     */
    public function setRetention($retention)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRetention', array($retention));

        return parent::setRetention($retention);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcceptance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcceptance', array());

        return parent::getAcceptance();
    }

    /**
     * {@inheritDoc}
     */
    public function setAcceptance($acceptance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcceptance', array($acceptance));

        return parent::setAcceptance($acceptance);
    }

    /**
     * {@inheritDoc}
     */
    public function getRetentionIs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRetentionIs', array());

        return parent::getRetentionIs();
    }

    /**
     * {@inheritDoc}
     */
    public function setRetentionIs($retentionIs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRetentionIs', array($retentionIs));

        return parent::setRetentionIs($retentionIs);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcceptanceIs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcceptanceIs', array());

        return parent::getAcceptanceIs();
    }

    /**
     * {@inheritDoc}
     */
    public function setAcceptanceIs($acceptanceIs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcceptanceIs', array($acceptanceIs));

        return parent::setAcceptanceIs($acceptanceIs);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssociateddAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssociateddAt', array());

        return parent::getAssociateddAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssociatedAt(\DateTime $associatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssociatedAt', array($associatedAt));

        return parent::setAssociatedAt($associatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkUserAssociated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkUserAssociated', array());

        return parent::getFkUserAssociated();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkUserAssociated(\Alae\Entity\User $fkUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkUserAssociated', array($fkUser));

        return parent::setFkUserAssociated($fkUser);
    }

}
