<?php

namespace DoctrineORMModule\Proxy\__CG__\Alae\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Batch extends \Alae\Entity\Batch implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'pkBatch', 'serial', 'fileName', 'fileSize', 'createdAt', 'updatedAt', 'validFlag', 'acceptedFlag', 'curveFlag', 'justification', 'validationDate', 'codeError', 'intercept', 'slope', 'correlationCoefficient', 'csTotal', 'qcTotal', 'ldqcTotal', 'hdqcTotal', 'csAcceptedTotal', 'qcAcceptedTotal', 'ldqcAcceptedTotal', 'hdqcAcceptedTotal', 'isCsQcAcceptedAvg', 'analyteConcentrationUnits', 'calculatedConcentrationUnits', 'fkParameter', 'fkAnalyte', 'fkUser', 'fkStudy');
        }

        return array('__isInitialized__', 'pkBatch', 'serial', 'fileName', 'fileSize', 'createdAt', 'updatedAt', 'validFlag', 'acceptedFlag', 'curveFlag', 'justification', 'validationDate', 'codeError', 'intercept', 'slope', 'correlationCoefficient', 'csTotal', 'qcTotal', 'ldqcTotal', 'hdqcTotal', 'csAcceptedTotal', 'qcAcceptedTotal', 'ldqcAcceptedTotal', 'hdqcAcceptedTotal', 'isCsQcAcceptedAvg', 'analyteConcentrationUnits', 'calculatedConcentrationUnits', 'fkParameter', 'fkAnalyte', 'fkUser', 'fkStudy');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Batch $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPkBatch()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getPkBatch();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPkBatch', array());

        return parent::getPkBatch();
    }

    /**
     * {@inheritDoc}
     */
    public function setPkBatch($pkBatch)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPkBatch', array($pkBatch));

        return parent::setPkBatch($pkBatch);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerial', array());

        return parent::getSerial();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerial($serial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerial', array($serial));

        return parent::setSerial($serial);
    }

    /**
     * {@inheritDoc}
     */
    public function getFileName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFileName', array());

        return parent::getFileName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFileName($fileName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFileName', array($fileName));

        return parent::setFileName($fileName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFileSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFileSize', array());

        return parent::getFileSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setFileSize($fileSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFileSize', array($fileSize));

        return parent::setFileSize($fileSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidFlag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidFlag', array());

        return parent::getValidFlag();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidFlag($validFlag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidFlag', array($validFlag));

        return parent::setValidFlag($validFlag);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurveFlag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurveFlag', array());

        return parent::getCurveFlag();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurveFlag($curveFlag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurveFlag', array($curveFlag));

        return parent::setCurveFlag($curveFlag);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcceptedFlag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcceptedFlag', array());

        return parent::getAcceptedFlag();
    }

    /**
     * {@inheritDoc}
     */
    public function setAcceptedFlag($acceptedFlag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcceptedFlag', array($acceptedFlag));

        return parent::setAcceptedFlag($acceptedFlag);
    }

    /**
     * {@inheritDoc}
     */
    public function getJustification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJustification', array());

        return parent::getJustification();
    }

    /**
     * {@inheritDoc}
     */
    public function setJustification($justification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJustification', array($justification));

        return parent::setJustification($justification);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidationDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidationDate', array());

        return parent::getValidationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidationDate(\DateTime $validationDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidationDate', array($validationDate));

        return parent::setValidationDate($validationDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeError()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeError', array());

        return parent::getCodeError();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeError($codeError)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeError', array($codeError));

        return parent::setCodeError($codeError);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntercept()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntercept', array());

        return parent::getIntercept();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntercept($intercept)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntercept', array($intercept));

        return parent::setIntercept($intercept);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlope()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlope', array());

        return parent::getSlope();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlope($slope)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlope', array($slope));

        return parent::setSlope($slope);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorrelationCoefficient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorrelationCoefficient', array());

        return parent::getCorrelationCoefficient();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorrelationCoefficient($correlationCoefficient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorrelationCoefficient', array($correlationCoefficient));

        return parent::setCorrelationCoefficient($correlationCoefficient);
    }

    /**
     * {@inheritDoc}
     */
    public function getCsTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCsTotal', array());

        return parent::getCsTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCsTotal($csTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCsTotal', array($csTotal));

        return parent::setCsTotal($csTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getQcTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQcTotal', array());

        return parent::getQcTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setQcTotal($qcTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQcTotal', array($qcTotal));

        return parent::setQcTotal($qcTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getLdqcTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLdqcTotal', array());

        return parent::getLdqcTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setLdqcTotal($ldqcTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLdqcTotal', array($ldqcTotal));

        return parent::setLdqcTotal($ldqcTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getHdqcTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHdqcTotal', array());

        return parent::getHdqcTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setHdqcTotal($hdqcTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHdqcTotal', array($hdqcTotal));

        return parent::setHdqcTotal($hdqcTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCsAcceptedTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCsAcceptedTotal', array());

        return parent::getCsAcceptedTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCsAcceptedTotal($csAcceptedTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCsAcceptedTotal', array($csAcceptedTotal));

        return parent::setCsAcceptedTotal($csAcceptedTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getQcAcceptedTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQcAcceptedTotal', array());

        return parent::getQcAcceptedTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setQcAcceptedTotal($qcAcceptedTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQcAcceptedTotal', array($qcAcceptedTotal));

        return parent::setQcAcceptedTotal($qcAcceptedTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getLdqcAcceptedTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLdqcAcceptedTotal', array());

        return parent::getLdqcAcceptedTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setLdqcAcceptedTotal($ldqcAcceptedTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLdqcAcceptedTotal', array($ldqcAcceptedTotal));

        return parent::setLdqcAcceptedTotal($ldqcAcceptedTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getHdqcAcceptedTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHdqcAcceptedTotal', array());

        return parent::getHdqcAcceptedTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setHdqcAcceptedTotal($hdqcAcceptedTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHdqcAcceptedTotal', array($hdqcAcceptedTotal));

        return parent::setHdqcAcceptedTotal($hdqcAcceptedTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsCsQcAcceptedAvg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsCsQcAcceptedAvg', array());

        return parent::getIsCsQcAcceptedAvg();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsCsQcAcceptedAvg($isCsQcAcceptedAvg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsCsQcAcceptedAvg', array($isCsQcAcceptedAvg));

        return parent::setIsCsQcAcceptedAvg($isCsQcAcceptedAvg);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnalyteConcentrationUnits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnalyteConcentrationUnits', array());

        return parent::getAnalyteConcentrationUnits();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnalyteConcentrationUnits($analyteConcentrationUnits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnalyteConcentrationUnits', array($analyteConcentrationUnits));

        return parent::setAnalyteConcentrationUnits($analyteConcentrationUnits);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalculatedConcentrationUnits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalculatedConcentrationUnits', array());

        return parent::getCalculatedConcentrationUnits();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalculatedConcentrationUnits($calculatedConcentrationUnits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalculatedConcentrationUnits', array($calculatedConcentrationUnits));

        return parent::setCalculatedConcentrationUnits($calculatedConcentrationUnits);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkParameter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkParameter', array());

        return parent::getFkParameter();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkParameter(\Alae\Entity\Parameter $fkParameter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkParameter', array($fkParameter));

        return parent::setFkParameter($fkParameter);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkAnalyte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkAnalyte', array());

        return parent::getFkAnalyte();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkAnalyte(\Alae\Entity\Analyte $fkAnalyte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkAnalyte', array($fkAnalyte));

        return parent::setFkAnalyte($fkAnalyte);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkUser', array());

        return parent::getFkUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkUser(\Alae\Entity\User $fkUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkUser', array($fkUser));

        return parent::setFkUser($fkUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkStudy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkStudy', array());

        return parent::getFkStudy();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkStudy(\Alae\Entity\Study $fkStudy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkStudy', array($fkStudy));

        return parent::setFkStudy($fkStudy);
    }

}
