<form id="datatable-form" action="" method="POST">
    <div id="datatable"></div>
    <input type="hidden" name="id" value="<?php echo $pkBatch; ?>"/>
</form>
<script>
    $("#datatable-form").validate();
</script>
<script>
    var createNumberIncr = 0;
    var data = <?php echo $data; ?>;
    var filters = <?php echo $header; ?>;
    var columns = <?php echo $columns; ?>;
    var editable = <?php echo $editable; ?>;
    var filtersHtml = '<?php echo $filters; ?>';
</script>
<script type="text/javascript" src="<?php echo $this->basePath() ?>/js/datatable.js"></script>
