<div id="logo">
    <img src="<?php echo $this->basePath() ?>/img/alaepeq.png">
</div>
<div id="cerrar">
    [<a href="<?php echo Alae\Service\Helper::getVarsConfig('base_url') . '/study/edit/' . $AnaStudy->getFkStudy()->getPkStudy() . '?state=' . $state; ?>">cerrar ficha</a>]&nbsp;
    [<a href="<?php echo Alae\Service\Helper::getVarsConfig('base_url') . '/index/menu' ?>">regresar al menú</a>]
</div>
<div id="<?php echo str_replace(" ", "_", strtolower($User->getFkProfile()->getName())) ?>">
    <form id="nominalconcentration-form" action="" method="POST">
        <div id="encab">
            <h2><?php echo $AnaStudy->getFkStudy()->getCode(); ?></h2>
        </div>
        <div class="nominalconcentration-form-buttons">
             <?php if ($User->isAdministrador() && !$isUnlock) : ?>
            <blockquote class="peq">
                Existen lotes validados con estas concentraciones nominales, si requiere modificaciones debe <strong>duplicar</strong> el estudio
            </blockquote>
            <?php endif; ?>
            <ul>
                <?php if(!$AnaStudy->getStatus() && ($User->isAdministrador() || $User->isDirectorEstudio())) : ?>
                <li>
                    <input type="submit" class="btn" value="guardar" />
                </li>
                    <?php if(count($cs_number) > 1 && count($qc_number) > 1 && !is_null($ldqc_number) && !is_null($hdqc_number)) : ?>
                    <li>
                        <button class="btn" type="button" onclick="changeStatus('/study/approvenc',<?php echo $AnaStudy->getPkAnalyteStudy(); ?>)"><span class="btn-validate"></span>aprobar</button>
                    </li>
                    <?php endif; ?>
                <?php endif; ?>
            </ul>
            <?php if ($AnaStudy->getStatus()) : ?>
                <p class="approve_notification"><?php printf("aprobado por: %s (%s). %s", $AnaStudy->getFkUserApprove()->getUsername(), $AnaStudy->getFkUserApprove()->getFkProfile()->getname(), $AnaStudy->getUpdatedAt()); ?></p>
            <?php endif; ?>
            <p>Arbol de Dilución: (1)</p>
        </div>
        <div style="display: none;"><ul id="errorBox"></ul></div>
        <div id="contenedor">
            <h5>Analito: <?php echo $AnaStudy->getFkAnalyte()->getName(); ?> (<?php echo $AnaStudy->getFkAnalyte()->getShortening(); ?>)</h5><br>
            <h4>Concentración Nominal de los Estándares de Calibración</h4>
            <ul>
                <?php for ($i = 0; $i < $AnaStudy->getCsNumber(); $i++) : ?>
                    <li>
                        <label>CS<?php echo $i + 1; ?>*</label>
                        <?php $numberCE = isset($cs_number[$i]) ? $cs_number[$i] : ""; ?>
                        <input type="text" value="<?php echo $numberCE; ?>" <?php echo $disabled; ?> name="cs_number[<?php echo $i; ?>]" class="nominalconcentration-form-number"/>
                    </li>
                <?php endfor; ?>
            </ul>
            <h4>Concentración Nominal de los Controles de Calidad</h4>
            <ul>
                <?php for ($i = 0; $i < $AnaStudy->getQcNumber(); $i++) : ?>
                    <li>
                        <label>QC<?php echo $i + 1; ?>*</label>
                        <?php
                        $numberQC = isset($qc_number[$i]) ? $qc_number[$i] : "";
                        ?>
                        <input type="text" value="<?php echo $numberQC; ?>" <?php echo $disabled; ?> name="qc_number[<?php echo $i; ?>]" class="nominalconcentration-form-number"/>
                    </li>
                <?php endfor; ?>
            </ul>
            <ul>
                <li>
                    <label>LDQC*</label>
                    <?php
                    	$numberLDQC = isset($ldqc_number) ? $ldqc_number : "";
                    ?>
                    <input type="text" value="<?php echo $ldqc_number; ?>" <?php echo $disabled; ?> name="ldqc_number" class="nominalconcentration-form-number"/>
                </li>
                <li>
                    <label>HDQC*</label>
                    <?php
                    	$numberHDQC = isset($hdqc_number) ? $hdqc_number : "";
                    ?>
                    <input type="text" value="<?php echo $numberHDQC; ?>" <?php echo $disabled; ?> name="hdqc_number" class="nominalconcentration-form-number"/>
                </li>
            </ul>

            <ul>
                <li>
                    <label>LLQC*</label>
                    <?php
                    	$numberLLQC = isset($llqc_number) ? $llqc_number : "";
                    ?>
                    <input type="text" value="<?php echo $llqc_number; ?>" <?php echo $disabled; ?> name="llqc_number" class="nominalconcentration-form-number"/>
                </li>
                <li>
                    <label>ULQC*</label>
                    <?php
                    	$numberULQC = isset($ulqc_number) ? $ulqc_number : "";
                    ?>
                    <input type="text" value="<?php echo $numberULQC; ?>" <?php echo $disabled; ?> name="hdqc_number" class="nominalconcentration-form-number"/>
                </li>
            </ul>

        </div>
        <input type="hidden" name="id" value="<?php echo $AnaStudy->getPkAnalyteStudy(); ?>" />
    </form>
    <script>
        jQuery.validator.addMethod("greaterThanZero", function(value, element) {
            return this.optional(element) || (parseFloat(value) > 0);
        }, "");
        jQuery.validator.addMethod("regex", function(value, element, params) {
                return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:,\d{3})+)?(?:\.\d+)?$/.test(value);
        }, "");
        jQuery.validator.addClassRules('nominalconcentration-form-number', {
            required: true,
            regex: true,
            greaterThanZero: true
        });

        $("#nominalconcentration-form").validate({
            errorLabelContainer: "#errorBox",
            wrapper: "li",
            submitHandler: function(form){
                answer = confirm("¿Desea guardar los cambios?");
                if (answer === true){
                    form.submit();
                    return true;
                }
                else{
                    return false;
                }
            }
        });
    </script>
    <script>
        function changeStatus(url, id)
        {
            answer = confirm('¿Desea aprobar las concentraciones nominales?');
            if (answer === true)
            {
                $( "#element_url" ).val(url);
                $( "#element_id" ).val(id);
                $( "#dialog-form" ).dialog( "open" );
            }
        }
    </script>
</div>
<div id="dialog-form" title="Firma digital">
    <div id="error-dialog-form" style="color: red; margin: 5px;font-size: 12px;"></div>
    <form id="verification-form" method="POST" action="<?php echo $this->basePath() ?>/index/autentication">
        <fieldset>
            <p><strong>Nombre y apellido: </strong><?php echo $User->getName(); ?></p>
            <p><strong>Fecha: </strong><?php echo date("d.m.Y H:i"); ?></p>
            <p><strong>Aprobado por: </strong><?php echo $User->getFkProfile()->getName(); ?></p>
            <label for="password">Contraseña</label>
            <input type="password" name="password" id="password" value="" class="text ui-widget-content ui-corner-all">
            <input type="hidden" name="element_url" id="element_url">
            <input type="hidden" name="element_id"  id="element_id">
            <input type="hidden" name="message"  id="message">
            <div style="margin: 10px;">
                <input type="submit" class="btn" value="verificar" />
                <button class="btn" type="button" onclick="closeForm()">cerrar</button>
            </div>
        </fieldset>
    </form>
</div>
<script>
    $(function() {
        $( "#dialog-form" ).dialog({
            autoOpen: false,
            height: 300,
            width: 350,
            modal: true,
        });

        $('#verification-form').ajaxForm({
            dataType:  'json',
            success:   processJson
        });
    });

    function processJson(data) {
        if (data.response)
        {
            closeForm();
            sendRequest();
        }
        else
        {
            $("#error-dialog-form").html(data.error);
        }
    }

    function closeForm()
    {
        $('#dialog-form').dialog('close');
        $('#verification-form').clearForm();
        $('#error-dialog-form').html("");
    }

    function sendRequest()
    {
        $.ajax
        ({
            type: "GET",
            dataType: "json",
            url: basePath + $( "#element_url" ).val(),
            data: {id: $( "#element_id" ).val()},
            success: function(data)
            {
                if (data.status)
                {
                    location.reload();
                }
                else
                {
                    alert(data.message);
                }
            }
        });
    }
</script>
