<div id="principal">
    <div id="cuerpo">
        <div id="central">
            <a href="<?php echo $this->url('index', array('action' => 'login')); ?>">
                <img src="<?php echo $this->basePath() . '/img/alaelogo.png' ?> "/>
            </a>
            <div id='login'>
                <h1>Inicio de sesi&oacute;n </h1>
                <form method='POST'  id="loginusr" action="">
                    <ul id="errorContainer" <?php if (!$inactive && !$incorrect) : ?>style="display: none;" <?php endif; ?>>
			<?php if ($inactive) : ?>
    			<li><label class='error auto'>Usuario <strong>NO REGISTRADO</strong> o Usuario <strong>INACTIVO</strong></label></li>
			<?php endif; ?>
			<?php if ($incorrect) : ?>
    			<li><label class='error auto'><strong>Nombre de usuario</strong> o <strong>Contraseña</strong> incorrecta</label></li>
			<?php endif; ?>
                    </ul>
                    <table>
                        <tr><td><label for="username">Nombre de usuario:</td>
                            <td><input id="username" name="username" type="text" ></tr><tr>
                            <td>
                                <label for="password"> Contrase&ntilde;a:
                            </td>
                            <td><input type="password" id="password" name="password">
                            </td>
                        </tr>
                        <tr>
                            <td>[<a href="<?php
				echo $this->url('user', array('action' => 'newaccount'));
				?>"><?php echo 'Solicitar cuenta'; ?></a>]</td>
                            <td >&nbsp;</td>
                        </tr><tr>

                            <td>[<a href="<?php echo $this->basePath() ?>/user/resetpass">Reinicializar contrase&ntilde;a</a>]</td>
                            <!-- para efectos de demostración, cambiar por SUBMIT  el botón a continuación-->
                            <td ><input type="submit" value="Iniciar sesión" id="entrar"></td>
                        </tr><tr>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>
<script>

    $("#loginusr").validate({
	rules: {
	    username: {
		required: true

	    },
	    password: {
		required: true


	    }
	},
	messages: {
	    username: {
		required: "El campo <strong>Nombre de usuario</strong> es obligatorio"

	    },
	    password: {
		required: "El campo <strong>Constraseña</strong> es obligatorio"
	    }

	},
	errorLabelContainer: "#errorContainer",
	wrapper: "li",
	errorPlacement: function(error, element) {

	}});

</script>