<div id="principal">
    <div id="cuerpo">
        <div id="izquierda">
            <img src="<?php echo $this->basePath() . '/img/alaelogo.png' ?> "  title="volver a contenido" />
        </div>
        <div id="derecha">
            <h2>menu principal</h2>
            <hr/>
            <ul>
                <?php if ($user->isAdministrador()) : ?>
                    <li><a href="<?php echo $this->basePath() ?>/study/index">Estudios abiertos</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/study/indexClose">Estudios cerrados</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/report/index">Estad&iacute;sticas</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/batch/unfilled">Lotes sin asignar</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/parameter/index">Parametrizaci&oacute;n (*)</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/study/verification">Parametrizaci&oacute;n Asociaci&oacute;n de muestras</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/report/audit">Audit Trail</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/index/logout">Salir de ALAE</a></li>
                <?php endif; ?>
                <?php if ($user->isUGC()) : ?>
                    <li><a href="<?php echo $this->basePath() ?>/study/index">Estudios abiertos</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/study/indexClose">Estudios cerrados</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/report/index">Estad&iacute;sticas</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/batch/unfilled">Lotes sin asignar</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/report/audit">Audit Trail</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/index/logout">Salir de ALAE</a></li>
                <?php endif; ?>
                <?php if ($user->isDirectorEstudio()) : ?>
                    <li><a href="<?php echo $this->basePath() ?>/study/index">Estudios abiertos</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/study/indexClose">Estudios cerrados</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/report/index">Estad&iacute;sticas</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/batch/unfilled">Lotes sin asignar</a></li>
                    <<li><a href="<?php echo $this->basePath() ?>/report/audit">Audit Trail</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/index/logout">Salir de ALAE</a></li>
                <?php endif; ?>
                <?php if ($user->isSustancias()) : ?>
                    <li><a href="<?php echo $this->basePath() ?>/report/audit">Audit Trail</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/index/logout">Salir de ALAE</a></li>
                <?php endif; ?>
                 <?php if ($user->isLaboratorio()) : ?>
                    <li><a href="<?php echo $this->basePath() ?>/study/index">Estudios abiertos</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/study/indexClose">Estudios cerrados</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/report/index">Estad&iacute;sticas</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/batch/unfilled">Lotes sin asignar</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/report/audit">Audit Trail</a></li>
                    <li><a href="<?php echo $this->basePath() ?>/index/logout">Salir de ALAE</a></li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</div>