<div id="logo">
    <img src="<?php echo $this->basePath() ?>/img/alaepeq.png">
</div>
<div id="cerrar">
    [<a href="<?php echo Alae\Service\Helper::getVarsConfig('base_url') . '/study/edit/' . $AnaStudy->getFkStudy()->getPkStudy() . '?state=' . $state; ?>">cerrar ficha</a>]&nbsp;
    [<a href="<?php echo Alae\Service\Helper::getVarsConfig('base_url') . '/index/menu' ?>">regresar al menú</a>]
</div>
<div id="create-analyte">
    <div id="encab">
        <h2>Asociación de muestras</h2>
        <h3>Estudio: <?php echo $AnaStudy->getFkStudy()->getCode(); ?></h3>
        <h3>Analito: <?php echo $AnaStudy->getFkAnalyte()->getName(); ?></h3>
        
    </div>
    <ul id="errorBox" <?php if ($error == "") : ?>style="display: none;"<?php endif; ?>>
        <?php echo $error ? $error : ""; ?>
    </ul>

    <div class="association-form-buttons">
            
            <ul>
            <?php if($AnaStudy->getFkUserAssociated()) { ?>
                <p class="approve_notification"><?php printf("aprobado por: %s (%s). %s", $AnaStudy->getFkUserAssociated()->getUsername(), $AnaStudy->getFkUserAssociated()->getFkProfile()->getname(), $AnaStudy->getAssociateddAt()); ?></p>
            <?php } else { ?>
               
                    <button class="btn" type="button" onclick="changeStatus('/study/associatedApprove',<?php echo $AnaStudy->getPkAnalyteStudy(); ?>)"><span class="btn-validate"></span>aprobar</button>
                
            <?php } ?>
            </ul>
        </div>

    <form id="datatable-form" action="#" method="POST">
        <div id="datatable" class="<?php echo str_replace(" ", "_", strtolower($user->getFkProfile()->getName())) ?>"></div>
    </form>
    <script>
        jQuery.validator.addClassRules('datatable-class-name', {
            required: true
        });
        jQuery.validator.addClassRules('datatable-class-shortname', {
            required: true
        });
        $("#datatable-form").validate({
            submitHandler: function(form){
                answer = confirm("¿Desea guardar los cambios?");
                if (answer === true){
                    form.submit();
                    return true;
                }
                else{
                    return false;
                }
            }
        });
    </script>
    <script>
        var createNumberIncr = 0;
        var data = <?php echo $data; ?>;
        var filters = <?php echo $header; ?>;
        var columns = <?php echo $columns; ?>;
        var editable = <?php echo $editable; ?>;
        var deleteUrl = basePath + '/study/deleteVerificationAssociation';
        var filtersHtml = '<?php echo $filters; ?>';
    </script>
    <script type="text/javascript" src="<?php echo $this->basePath() ?>/js/datatable.js"></script>
</div>
<script>
        function changeStatus(url, id)
        {
            answer = confirm('¿Desea aprobar la asociación de concentraciones nominales?');
            if (answer === true)
            {
                $( "#element_url" ).val(url);
                $( "#element_id" ).val(id);
                $( "#dialog-form" ).dialog( "open" );
            }
        }
    </script>
    <div id="dialog-form" title="Firma digital">
    <div id="error-dialog-form" style="color: red; margin: 5px;font-size: 12px;"></div>
    <form id="verification-form" method="POST" action="<?php echo $this->basePath() ?>/index/autentication">
        <fieldset>
            <p><strong>Nombre y apellido: </strong><?php echo $user->getName(); ?></p>
            <p><strong>Fecha: </strong><?php echo date("d.m.Y H:i"); ?></p>
            <p><strong>Aprobado por: </strong><?php echo $user->getFkProfile()->getName(); ?></p>
            <label for="password">Contraseña</label>
            <input type="password" name="password" id="password" value="" class="text ui-widget-content ui-corner-all">
            <input type="hidden" name="element_url" id="element_url">
            <input type="hidden" name="element_id"  id="element_id">
            <input type="hidden" name="message"  id="message">
            <div style="margin: 10px;">
                <input type="submit" class="btn" value="verificar" />
                <button class="btn" type="button" onclick="closeForm()">cerrar</button>
            </div>
        </fieldset>
    </form>
</div>
<script>
    $(function() {
        $( "#dialog-form" ).dialog({
            autoOpen: false,
            height: 300,
            width: 350,
            modal: true,
        });

        $('#verification-form').ajaxForm({
            dataType:  'json',
            success:   processJson
        });
    });

    function processJson(data) {
        if (data.response)
        {
            closeForm();
            sendRequest();
        }
        else
        {
            $("#error-dialog-form").html(data.error);
        }
    }

    function closeForm()
    {
        $('#dialog-form').dialog('close');
        $('#verification-form').clearForm();
        $('#error-dialog-form').html("");
    }

    function sendRequest()
    {
        $.ajax
        ({
            type: "GET",
            dataType: "json",
            url: basePath + $( "#element_url" ).val(),
            data: {id: $( "#element_id" ).val()},
            success: function(data)
            {
                if (data.status)
                {
                    location.reload();
                }
                else
                {
                    alert(data.message);
                }
            }
        });
    }
</script>
