<div id="logo">
    <img src="<?php echo $this->basePath() ?>/img/alaepeq.png">
</div>
<div id="cerrar">
[<a href="<?php echo Alae\Service\Helper::getVarsConfig('base_url') . '/study/edit/' . $AnaStudy->getFkStudy()->getPkStudy() . '?state=' . $state; ?>">cerrar ficha</a>]&nbsp;
    [<a href="<?php echo Alae\Service\Helper::getVarsConfig('base_url') . '/index/menu' ?>">regresar al menú</a>]
</div>
<div id="create-analyte">
    <div id="encab">
        <h2>Samples</h2>
    </div>
    <ul id="errorBox" <?php if ($error == "") : ?>style="display: none;"<?php endif; ?>>
        <?php echo $error ? $error : ""; ?>
    </ul>
    <form id="datatable-form" action="#" method="POST">
        <div id="datatable" class="<?php echo str_replace(" ", "_", strtolower($user->getFkProfile()->getName())) ?>"></div>
    </form>
    <script>
        jQuery.validator.addClassRules('datatable-class-name', {
            required: true
        });
        jQuery.validator.addClassRules('datatable-class-shortname', {
            required: true
        });
        $("#datatable-form").validate({
            submitHandler: function(form){
                answer = confirm("¿Desea guardar los cambios?");
                if (answer === true){
                    form.submit();
                    return true;
                }
                else{
                    return false;
                }
            }
        });
    </script>
    <script>
        var createNumberIncr = 0;
        var data = <?php echo $data; ?>;
        var filters = <?php echo $header; ?>;
        var columns = <?php echo $columns; ?>;
        var editable = <?php echo $editable; ?>;
        var filtersHtml = '<?php echo $filters; ?>';
    </script>
    <script type="text/javascript" src="<?php echo $this->basePath() ?>/js/datatable.js"></script>
</div>