<?php echo $this->doctype(); ?>
<html lang="es">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php echo $this->headTitle('ALAE')->setSeparator(' - ')->setAutoEscape(false) ?>
	<?php
	echo $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>
	<!-- Le styles -->
	<?php
	echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
		->prependStylesheet($this->basePath() . '/css/style.css')
		->prependStylesheet($this->basePath() . '/css/alae.css')
		->prependStylesheet($this->basePath() . '/css/datatable.css')
        ->prependStylesheet($this->basePath() . '/css/reports.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-select.min.css')
        ->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
	?>

    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="/alae/alae/public/css/bootstrap.min.css">

	<!-- Scripts -->
	<?php
	echo $this->headScript()
		->prependFile($this->basePath() . '/js/script.js')
		->prependFile($this->basePath() . '/js/additional-methods.min.js')
		->prependFile($this->basePath() . '/js/jquery.validate.min.js')
		->prependFile($this->basePath() . '/js/jquery.js')
		->prependFile($this->basePath() . '/js/yui.min.js')
        ->prependFile($this->basePath() . '/js/jquery-1.10.2.min.js')
        ->prependFile($this->basePath() . '/js/jquery.form.min.js')
        ->prependFile($this->basePath() . '/js/jquery-ui.js')
        ->prependFile($this->basePath() . '/js/bootstrap-select.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
		//->prependFile($this->basePath() . '/public/css/style.css');
	?>


    

	<script>
        var basePath = '<?php echo $this->basePath() ?>';
        
        </script>
<!--
        <script src="http://yui.yahooapis.com/3.14.0/build/yui/yui-min.js"></script>
        <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"></script>
        
        <script src="/alae/validaciones/public/js/bootstrap.min.js"></script> 

        <script src="/alae/validaciones/public/js/bootstrap-select.min.js"></script>


        <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script> 
       <script src="http://malsup.github.com/jquery.form.js"></script>

       <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js" integrity="sha384-qlmct0AOBiA2VPZkMY3+2WqkHtIQ9lSdAsAn5RUJD/3vA5MKDgSGcdmIv4ycVxyn" crossorigin="anonymous"></script>

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script> 

        <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
-->







        <script src="/alae/validaciones/public/js/yui-min.js"></script>

        <script src="/alae/validaciones/public/js/jquery-1.10.2.min.js"></script>

        <script src="/alae/validaciones/public/js/jquery.validate.min.js"></script>
<!--        
        <script src="/alae/validaciones/public/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script> 
        <script src="/alae/validaciones/public/js/jquery.form.min.js" integrity="sha384-qlmct0AOBiA2VPZkMY3+2WqkHtIQ9lSdAsAn5RUJD/3vA5MKDgSGcdmIv4ycVxyn" crossorigin="anonymous"></script>
-->       
        
        <script src="/alae/validaciones/public/js/bootstrap.min.js"></script>
        <script src="/alae/validaciones/public/js/bootstrap-select.min.js"></script>

        <script src="/alae/validaciones/public/js/jquery-ui.js"></script>
        <script src="/alae/validaciones/public/js/jquery.form.js"></script>
        <script src="/alae/validaciones/public/js/jquery.form.min.js"></script>
<!--
        <script type="text/javascript" src="/alae/validaciones/public/js/datatable.js"></script>-->

      <!--Latest compiled and minified CSS 
      <link rel="stylesheet" type="text/css" href="/alae/validaciones/public/css/alae.css">
      <link rel="stylesheet" type="text/css" href="/alae/validaciones/public/css/bootstrap.css">
      <link rel="stylesheet" type="text/css" href="/alae/validaciones/public/css/bootstrap.min.css">
      <link rel="stylesheet" type="text/css" href="/alae/validaciones/public/css/bootstrap-select.min.css">
      <link rel="stylesheet" type="text/css" href="/alae/validaciones/public/css/bootstrap-theme.css">
      <link rel="stylesheet" type="text/css" href="/alae/validaciones/public/css/bootstrap-theme.min.css">
      <link rel="stylesheet" type="text/css" href="/alae/validaciones/public/css/content.css">
      <link rel="stylesheet" type="text/css" href="/alae/validaciones/public/css/datatable.css">
      <link rel="stylesheet" type="text/css" href="/alae/validaciones/public/css/jquery-ui.css">
      <link rel="stylesheet" type="text/css" href="/alae/validaciones/public/css/reports.css">
      <link rel="stylesheet" type="text/css" href="/alae/validaciones/public/css/style.css">
-->


    </head>
    <body>
        <div id="container">
	    <?php echo $this->content; ?>
	    <div id="pie">
                <p>
		    <?php echo Alae\Service\Helper::getUserSession() . '<B> VALIDACIONES </B>'; ?>
                </p>
                <p>
                    ALAE Software. Copyright © Anapharm Europe, V.2.8 <?php echo "27-AGO-2024"; ?>
                </p>
            </div>
	</div>
        <?php if (Alae\Service\Helper::getUserSession()) : ?>
            <script>
            var close;
            $(document).on('mousemove', function(e){
                clearTimeout(close);
                closeSession();
            });
            window.onload = function()
            {
                closeSession();
            }

            function closeSession()
            {
                close = setTimeout("window.location.href = '" + basePath + "/index/logout';",900000);
            }
            </script>
        <?php endif; ?>
    </body>
</html>



