<div id="cerrar">
    <a href="<?php echo $this->url('index', array('action' => 'login')); ?>">
        <img title="regresar a la pantalla de login" src="<?php echo $this->basePath(); ?>/img/close.png"/>
    </a>
</div>
<div id="principal">
    <div id="cuerpo">
	<div id="central">
	    <a href="<?php echo $this->url('user', array('action' => 'login')); ?>">
		<img src="<?php echo $this->basePath() . '/img/alaepeq.png'; ?>"/>
	    </a>
	    <?php if ($showForm) : ?>
    	    <div id="login">
    		<h1>Indique su contraseña</h1>
    		<form method="POST"  id="register" action="">
    		    <input type="hidden" name="id" value="<?php echo $pkUser ?>">
                    <ul id="errorContainer" <?php if (!$error) : ?>style="display: none;"<?php endif; ?>>
                        <?php if ($error) : ?>
                        <li>El código de activación ha caducado...</li>
                        <?php endif; ?>
                    </ul>
    		    <table>
    			<tbody>
    			    <tr>
    				<td>Nombre de usuario:</td>
    				<td><?php echo $username ?></td>
    			    </tr>
    			    <tr>
    				<td>Contraseña (*):</td>
    				<td><input type="password" id="pwd" name="pwd"></td>
    			    </tr>
    			    <tr>
    				<td>Confirmar contraseña (*):</td>
    				<td><input name ="password" type="password" id="password" name="password"></td>
    			    </tr>
    			    <tr>
    				<td>Correo electrónico:</td>
    				<td><?php echo $email ?></td>
    			    </tr>
    			    <tr>
    				<td>Nombre real (*):</td>
    				<td><input type="text" id="name"  name ="name" name="name" ></td>
    			    </tr>
    			    <tr>
    				<td><input type="submit" value="Actualizar usuario"></td>
    			    </tr>
    			    <tr>
    				<td colspan="2">
    				    <p class="peq" style="line-height:1.3em;">
    					El acceso a ALAE requiere de aprobación.<br>
    					Una vez que el Administrador de la Aplicación le asigne su perfil, <br>podrá tener acceso a ALAE con el nombre de usuario y la contraseña indicados.<br>
    				    </p>
    				</td>
    			    </tr>
    			</tbody>
    		    </table>
    		</form>
                <script>
                    $("#register").validate({
                        rules: {
                            pwd: {
                                required: true,
                                minlength: 6,
                            },
                            name: {
                                required: true
                            },
                            password: {
                                required: true, equalTo: "#pwd",
                            }
                        },
                        messages: {
                            pwd: {
                                required: "La <strong>Contraseña</strong> es obligatoria",
                                minlength: "La <strong>Contraseña</strong> debe contener un mínimo de 6 carácteres"
                            },
                            name: {
                                required: "El <strong>Nombre de usuario</strong> es obligatorio"
                            },
                            password: {
                                required: "El <strong>Confirmar contraseña</strong> es obligatorio",
                                equalTo: "Las contraseñas no coinciden"
                            }

                        },
                        errorLabelContainer: "#errorContainer",
                        wrapper: "li",
                        errorPlacement: function(error, element) {
                            $(".auto").hide();
                        },
                        submitHandler: function(form){
                            answer = confirm("¿Desea guardar los cambios?");
                            if (answer === true){
                                form.submit();
                                return true;
                            }
                            else{
                                return false;
                            }
                        }
                    });
                </script>
    	    </div>
	    <?php endif; ?>
	</div>
    </div>
</div>