
<div id="principal">
    <div id="logo">
        <img src="<?php echo $this->basePath() ?>/img/alaepeq.png">
    </div>
    <div id="cerrar">
        [<a href="<?php echo Alae\Service\Helper::getVarsConfig('base_url') . '/index/menu' ?>">regresar al menú</a>]
    </div>
    <div id="cuerpo">
        <div id="centrado" style="font-size:1em;">
            <div id="reports">
                <div id="encab">
                    <h2>informes estad&iacute;sticos</h2>
                </div>
                <?php if($error) : ?>
                <ul id="errorBox"><li>No se ha generado información para este reporte</li></ul>
                <?php endif; ?>
                <p>
                    <label>C&oacute;digo del Estudio:</label>
                    <select id="study"class="selectpicker" data-live-search="true" title="Seleccione un estudio de la lista">
                        <?php foreach ($studies as $study) : ?>
                        <option value="<?php echo $study->getPkStudy(); ?>"><?php echo $study->getCode(); ?></option>
                        <?php endforeach; ?>
                    </select>
                </p>
                <p id="ajax1" style="display: none">
                    <label>Analito (*): </label>
                    <select id="analyte" class="selectpicker" data-live-search="true" title="Seleccione un analito de lista"></select>
                </p>
                <p id="ajax2" style="display: none">
                    <label>Lote (*): </label>
                    <select id="batch" class="selectpicker" data-live-search="true" title="Seleccione un lote de la lista"></select>
                </p>
                <h4>Seleccione el informe deseado:</h4>
                <ul class="pdf"><br/>
                    <li><a onclick="reports('<?php echo $this->basePath() ?>/report/r1', false, false);">01. Información General de un Estudio</a></li>
                    <li><a onclick="reports('<?php echo $this->basePath() ?>/report/r2', true, true);">02. Tabla ALAE de cada lote analítico(*)</a></li>
                    <li><a onclick="reports('<?php echo $this->basePath() ?>/report/r3', true, false);">03. Resumen de Lotes de un Estudio  (*)</a></li>
                    <li><a onclick="reports('<?php echo $this->basePath() ?>/report/r4', true, false);">04. Listado de Muestras a Repetir (*)</a></li>
                </ul>
                <ul class="xls">
                    <li><a onclick="reports('<?php echo $this->basePath() ?>/report/r11', true, false);">05. Listado de Muestras a Repetir (*)</a></li>
                    <li><a onclick="reports('<?php echo $this->basePath() ?>/report/r5', true, false);">06. Summary of Calibration Curve Parameters (*)</a></li>
                    <li><a onclick="reports('<?php echo $this->basePath() ?>/report/r6', true, false);">07. Back-Calculated Concentration of Calibration Standard (*)</a></li>
                    <li><a onclick="reports('<?php echo $this->basePath() ?>/report/r7', true, false);">08. Calculated % Nominal Concentration of Calibration Standards (*)</a></li>
                    <li><a onclick="reports('<?php echo $this->basePath() ?>/report/r8', true, false);">09. Calculated Concentration & % Nominal of Quality Control Samples (*)</a></li>
                    <!--<li><a onclick="reports('<?php echo $this->basePath() ?>/report/r8', true, false);">09. Between-Run Accuracy and Precision of Quality Control Samples (*)</a></li>-->
                    <li><a onclick="reports('<?php echo $this->basePath() ?>/report/r9', true, false);">10. Between-Run Accuracy and Precision of Dilution Quality Control Samples (*)</a></li>
                    <li><a onclick="reports('<?php echo $this->basePath() ?>/report/r11', true, false);">11. Listado de muestras (*)</a></li>
                </ul>
                <ul class="txt">
                    <li><a onclick="reports('<?php echo $this->basePath() ?>/report/rtxt', true, true);">01. Tabla ALAE de cada lote analítico txt(*)</a></li>
                </ul>
            </div>
        </div>
        <blockquote class="peq">
            Los reportes con (*) requieren que se seleccione un Analito de la lista deplegable <strong>Analito (*)</strong>
        </blockquote>
    </div>
</div>
<script>
    function reports(url, isAnalyte, isBatch)
    {
        var isRedirect = true;

        if($("#study").val() !== "-1")
        {
            url = url + "?id=" + $("#study").val();
            if (isAnalyte && $("#analyte").val() !== null)
            {
                url = url + "&an=" + $("#analyte").val();

                if(isBatch && $("#batch").val() > 0)
                {
                    url = url + "&ba=" + $("#batch").val();
                }
                else if(!isBatch)
                {
                    isRedirect = true;
                }
                else
                {
                    alert("Debe seleccionar un lote");
                    isRedirect = false;
                }
            }
            else if(!isAnalyte)
            {
                isRedirect = true;
            }
            else
            {
                alert("Debe seleccionar un Analito");
                isRedirect = false;
            }

            if(isRedirect)
            {
                window.location = url;
            }
        }
        else
        {
            alert("Debe seleccionar un Estudio");
        }
    }

    $('#study').on('change', function() {
	var optionSelected = $("option:selected", this);
	var id = this.value;
        if(id > 0)
        {
            $.ajax
            ({
                type: "GET",
                dataType: "json",
                url: basePath + "/report/ajxstudy",
                data: {id: id},
                success: function(data)
                {
                    //
                    
                    
                    $('#analyte').html(data.data);
                    //$('#analyte').selectpicker();
                    $('#analyte').selectpicker('refresh');
                    $('#ajax1').show();
                    $('#analyte').show();
                    $('#ajax2').hide();
                  
                    $('#batch').hide();
                }
            });
        }
        else
        {
            $('#ajax1').hide();
            $('#analyte').hide();
            $('#ajax2').hide();
            $('#batch').hide();
        }
    });

    $('#analyte').on('change', function() {
    var optionSelected = $("option:selected", this);
	var an = this.value;
        if(an > 0)
        {
            $.ajax
            ({
                type: "GET",
                dataType: "json",
                url: basePath + "/report/ajxbatch",
                data: {id: $('#study').val(), an: an},
                success: function(data)
                {
                   
                    $('#batch').html(data.data);
                    $('#batch').selectpicker('refresh');
                    $('#ajax2').show();
                    $('#batch').show();
                }
            });
        }
        else
        {
            $('#ajax2').hide();
            $('#batch').hide();
        }
    });
</script>
