<nobreak>
<div>

<table border="0" cellspacing="0" cellpadding="0"  style="padding:20px; width:100%;background-color:#fff;text-align:center; font-size:20px;">
<tr>
<td>
<strong>INFORMACIÓN GENERAL DE UN ESTUDIO</strong>
</td>
</tr>
</table>
    
    <table border="0" cellspacing="0" cellpadding="0" style="padding:20px; width:100%;margin-top:10px;text-align:center">
        <tr>
            <td align="center" height="20" bgcolor="#252525" style="width:10%;color:#fff;text-align:justify;border: white 1px solid;">
                <strong>Código del Estudio</strong>
            </td>
            <td align="center" height="20" style="border: black 1px solid;">
                <?php echo $study->getCode(); ?>
            </td>
        </tr>

        <tr>
            <td align="center" height="20" bgcolor="#252525" style="width:10%;color:#fff;text-align:justify;border: white 1px solid;">
                <strong>Nº de Analitos</strong>
            </td>
            <td   align="center" height="20" style="border: black 1px solid;">
                <?php echo $counterAnalyte; ?>
            </td>
        </tr>

        <tr>
            <td align="center" height="20" bgcolor="#252525" style="width:10%;color:#fff;text-align:justify;border: white 1px solid;">
                <strong>Arbol de Dilución Nº</strong>
            </td>
            <td   align="center" height="20" style="border: black 1px solid;">
                <?php echo $study->getFkDilutionTree(); ?>
            </td>
        </tr>
        <tr>
            <td align="center" height="20" bgcolor="#252525" style="width:10%;color:#fff;text-align:justify;border: white 1px solid;">
                <strong>Validación</strong>
            </td>
            <td   align="center" height="20" style="border: black 1px solid;">
                <?php if ($validation == 0)
                {
                    echo "Parcial";
                }
                else
                {
                    echo "Parcial";
                }
                ?>
            </td>
        </tr>
        <tr>
            <td align="center" height="20" bgcolor="#252525" style="width:10%;color:#fff;text-align:justify;border: white 1px solid;">
                <strong>Verificación V13</strong>
            </td>
            <td   align="center" height="20" style="border: black 1px solid;">
            <?php if ($verification == 0)
                {
                    echo "No";
                }
                else
                {
                    echo "Sí";
                }
                ?>
            </td>
        </tr>
    </table>

    <table border="0" cellspacing="0" cellpadding="0" style="padding:20px; width:100%;margin-top:10px;text-align:center">

        <?php if ($validation == 0)
        {
            ?>
                <tr>
                    <td colspan="1" bgcolor="#000000"></td>
                    <td align="center" width ="100" bgcolor="#000000" style="color:#ffffff;border: black 1px solid;font-size:11px;">
                        <strong>Analito</strong>
                    </td>
                    <td colspan="1" bgcolor="#000000"></td>
                    <td  align="center" width ="100" bgcolor="#000000" style="color:#ffffff;border: black 1px solid;font-size:11px;">
                        <strong>Patrón interno</strong>
                    </td>
                    <td bgcolor="#000000"></td>
                </tr>
            <?php
        }
        else
        {
            if($verification == 1)
            {
            ?>
                <tr>
                    <td colspan="3" bgcolor="#000000"></td>
                    <td align="center" width ="100" bgcolor="#000000" style="color:#ffffff;border: black 1px solid;font-size:11px;">
                        <strong>Analito</strong>
                    </td>
                    <td colspan="5" bgcolor="#000000"></td>
                    <td  align="center" width ="100" bgcolor="#000000" style="color:#ffffff;border: black 1px solid;font-size:11px;">
                        <strong>Patrón interno</strong>
                    </td>
                    <td colspan="5" bgcolor="#000000"></td>
                </tr>
            <?php
            }
            else
            {
                ?>
                <tr>
                    <td colspan="1" bgcolor="#000000"></td>
                    <td align="center" width ="100" bgcolor="#000000" style="color:#ffffff;border: black 1px solid;font-size:11px;">
                        <strong>Analito</strong>
                    </td>
                    <td colspan="1" bgcolor="#000000"></td>
                    <td  align="center" width ="100" bgcolor="#000000" style="color:#ffffff;border: black 1px solid;font-size:11px;">
                        <strong>Patrón interno</strong>
                    </td>
                    <td bgcolor="#000000"></td>
                </tr>
                <?php 
            }
        }
        ?>

        <tr>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"></td>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Analito</strong></td>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Abr.</strong></td>
            <?php if ($validation == 0)
            {

            }
            else
            {
                if($verification == 1)
                {
                    ?>
                        <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>M. Aceptación</strong></td>
                        <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Retención</strong></td>
                        <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Tr. Min</strong></td>
                        <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Tr. Max</strong></td>
                    <?php

                }
                else
                {
                    
                }
            }
            ?>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Patrón interno (IS)</strong></td>
            <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Abr.</strong></td>
            <?php if ($validation == 0)
            {

            }
            else
            {
                if($verification == 1)
                {
                    ?>
                        <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>M. Aceptación</strong></td>
                        <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Retención</strong></td>
                        <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Tr. Min (IS)</strong></td>
                        <td  align="center"  bgcolor="#D8D8D8"   style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Tr. Max (IS)</strong></td>
            <?php

                }
                else
                {
                    
                }
            }
            ?>
        </tr>

        <?php $count = 1; foreach ($analytes as $anaStudy) : ?>
        <tr>
            <td  align="center"  width ="100" style="color:#000000;padding:5px;border: black 1px solid;font-size:11px;">
                <?php echo $count; ?>
            </td>
            <td  align="center" width ="100"   style="color:#000000;border: black 1px solid;font-size:11px;">
                <?php echo $anaStudy->getFkAnalyte()->getName(); ?>
            </td>
            <td  align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                <?php echo $anaStudy->getFkAnalyte()->getShortening(); ?>
            </td>
            <?php if ($validation == 0)
            {

            }
            else
            {
                if($verification == 1)
                {
                    ?>
                        <td  align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                        <?php echo number_format($anaStudy->getAcceptance(),2,'.',''); ?>
                    </td>
                    <td  align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                        <?php echo number_format($anaStudy->getRetention(),2,'.',''); ?>
                    </td>
                    <td  align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                        <?php $min = $anaStudy->getRetention() - ($anaStudy->getAcceptance() * $anaStudy->getRetention() / 100);?>
                        <?php echo number_format($min,2,'.',''); ?>
                    </td>
                    <td  align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                        <?php $max = $anaStudy->getRetention() + ($anaStudy->getAcceptance() * $anaStudy->getRetention() / 100); ?>
                        <?php echo number_format($max,2,'.',''); ?>
                    </td>
                <?php
                }
                else
                {
                    
                }
            }
            ?>
            
            <td  align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                <?php echo $anaStudy->getFkAnalyteIs()->getName(); ?>
            </td>
            <td  align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                <?php echo $anaStudy->getFkAnalyteIs()->getShortening(); ?>
            </td>
            <?php if ($validation == 0)
            {

            }
            else
            {
                if($verification == 1)
                {
                ?>
                    <td  align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                        <?php echo number_format($anaStudy->getAcceptanceIs(),2,'.',''); ?>
                    </td>
                    <td  align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                        <?php echo number_format($anaStudy->getRetentionIs(),2,'.',''); ?>
                    </td>
                    <td  align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                        <?php $min_is = $anaStudy->getRetentionIs() - ($anaStudy->getAcceptanceIs() * $anaStudy->getRetentionIs() / 100); ?>
                        <?php echo number_format($min_is,2,'.',''); ?>
                    </td>
                    <td  align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                        <?php $max_is = $anaStudy->getRetentionIs() + ($anaStudy->getAcceptanceIs() * $anaStudy->getRetentionIs() / 100); ?>
                        <?php echo number_format($max_is,2,'.',''); ?>
                    </td>
                <?php
                }
                else
                {
                    
                }
            }
            ?>
        </tr>
        <?php $count++; endforeach; ?>
    </table>

    <table border="0" cellspacing="0" cellpadding="0" style="padding:20px; width:100%;margin-top:10px;text-align:center">
        <tr>
            <td align="center" width ="100" colspan="4" bgcolor="#000000" style="color:#ffffff;border: black 1px solid;font-size:11px;">
                <strong>Concentración Nominal de los Estándares de Calibración</strong>
            </td>
        </tr>

        <tr>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Analito</strong></td>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Unidad</strong></td>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Muestra</strong></td>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Concentración nominal</strong></td>
        </tr>
        <?php  foreach ($cs_values as $cs_value) : ?>
            <tr>
                <td align="left" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $cs_value["analyte"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $cs_value["unit"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $cs_value["sample"]; ?></strong>
                </td>
                <td align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $cs_value["value"]; ?></strong>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>

    <table border="0" cellspacing="0" cellpadding="0" style="padding:20px; width:100%;margin-top:10px;text-align:center">
        <tr>
            <td align="center" width ="100" colspan="4" bgcolor="#000000" style="color:#ffffff;border: black 1px solid;font-size:11px;">
                <strong>Concentración Nominal de los Controles de Calidad</strong>
            </td>
        </tr>
        <tr>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Analito</strong></td>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Unidad</strong></td>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Muestra</strong></td>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Concentración nominal</strong></td>
        </tr>
        <?php  foreach ($qc_values as $qc_value) : ?>
            <tr>
                <td align="left" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $qc_value["analyte"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $qc_value["unit"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $qc_value["sample"]; ?></strong>
                </td>
                <td align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $qc_value["value"]; ?></strong>
                </td>
            </tr>
        <?php endforeach; ?>

        <?php  foreach ($ldqc_values as $ldqc_value) : ?>
            <tr>
                <td align="left" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $ldqc_value["analyte"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $ldqc_value["unit"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $ldqc_value["sample"]; ?></strong>
                </td>
                <td align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $ldqc_value["value"]; ?></strong>
                </td>
            </tr>
        <?php endforeach; ?>

        <?php  foreach ($hdqc_values as $hdqc_value) : ?>
            <tr>
                <td align="left" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $hdqc_value["analyte"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $hdqc_value["unit"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $hdqc_value["sample"]; ?></strong>
                </td>
                <td align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $hdqc_value["value"]; ?></strong>
                </td>
            </tr>
        <?php endforeach; ?>

        <?php  foreach ($llqc_values as $llqc_value) : ?>
            <tr>
                <td align="left" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $llqc_value["analyte"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $llqc_value["unit"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $llqc_value["sample"]; ?></strong>
                </td>
                <td align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $llqc_value["value"]; ?></strong>
                </td>
            </tr>
        <?php endforeach; ?>

        <?php  foreach ($ulqc_values as $ulqc_value) : ?>
            <tr>
                <td align="left" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $ulqc_value["analyte"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $ulqc_value["unit"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $ulqc_value["sample"]; ?></strong>
                </td>
                <td align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $ulqc_value["value"]; ?></strong>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>

    <table border="0" cellspacing="0" cellpadding="0" style="padding:20px; width:100%;margin-top:10px;text-align:center">
        <tr>
            <td align="center" width ="100" colspan="4" bgcolor="#000000" style="color:#ffffff;border: black 1px solid;font-size:11px;">
                <strong>Muestras asociadas</strong>
            </td>
        </tr>
        <tr>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Analito</strong></td>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Muestra</strong></td>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Asociación</strong></td>
            <td  align="center"  bgcolor="#D8D8D8" style="color:#000000;font-size:11px;padding:5px;border: black 1px solid;"><strong>Valor</strong></td>
        </tr>
        <?php  foreach ($verifications as $verification) : ?>
            <tr>
                <td align="left" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $verification["analyte"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $verification["sample"]; ?></strong>
                </td>
                <td align="center" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $verification["associated"]; ?></strong>
                </td>
                <td align="right" width ="100"  style="color:#000000;border: black 1px solid;font-size:11px;">
                    <strong><?php echo $verification["value"]; ?></strong>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>

    <table border="0" cellspacing="0" cellpadding="0" style="padding:20px; width:100%;margin-top:10px;text-align:center">
        <tr>
            <td   align="left" height=2 bgcolor="#ffffff" style="color:#000000;font-size:11px;padding:10px">&nbsp;</td>
        </tr>
        <tr>
            <td   height=20  height="20" bgcolor="#000000" style="color:#ffffff;font-size:11px;padding:10px">
                <strong>Elaboración</strong>
            </td>
            <td   height=20  height="20"  style="color:#000000;font-size:11px;padding:10px">
                (<?php echo $study->getFkUser()->getUsername(); ?>)
            </td>
        </tr>
        <tr>
            <td   height="20" bgcolor="#000000" style="color:#ffffff;font-size:11px;padding:10px">
                Aprobación:
            </td>
            <td   height=20   style="color:#000000;font-size:11px;padding:10px">
                (<?php echo !is_null($study->getFkUserApprove()) ? $study->getFkUserApprove()->getUsername() : "Sin aprobación"; ?>)
            </td>
        </tr>
        <tr>
            <td align="center" bgcolor="#fff" style="text-align:center;">
                 <?php echo date("d.m.Y H:i:s"); ?>
            </td>
        </tr>
    </table>

</div>
</nobreak>