<nobreak>

	<div class="table-container">
	<table style="width:600px;background-color:#fff;padding:40px 40px 0px 40px;font: arial;margin-right:100px">
		<tr>
            <td colspan="4">
                <h3>TABLA DE RESULTADOS ALAE</h3>
            </td>
        </tr>
        <tr>
            <td width="150"  align="left" height="20"  style="font-size: 13px;">
                Código del estudio:
            </td>
            <td width="150" align="left"  height="20" style="">
                <?php echo $batch->getFkStudy()->getCode(); ?>
            </td>
            <td width="150" align="left"  style="font-size: 13px;font-weight: bold;">
                Parámetros de la Curva de Calibrado (Y= mX+b)
            </td>
            <td width="150"  align="left"  height="20">
            </td>
        </tr>
        <tr>
            <td  align="left" height="20"   style="font-size: 13px;">
                Analito:
            </td>
            <td  align="left"  height="20" style="">
                <?php echo $batch->getFkAnalyte()->getName(); ?>
            </td>
            <td    height="20"  align="left" style="font-size: 13px;">
                m=
            </td>            
            <td   align="left"  height="20">
            
            <?php //echo number_format($batch->getSlope(), 3, '.', ''); 
            echo Alae\Service\Helper::getformatDecimal($batch->getSlope()); ?>                
            </td>
        </tr>
        <tr>
        	<td align="left" height="20"   style="font-size: 13px;">
                Nombre del archivo exportado:
            </td>
            <td  height="20" align="left" style="">
                <?php echo $batch->getFileName(); ?>
            </td>
            <td   align="left" height="20"   style="font-size: 13px;font-weight: bold">
                b=
            </td>
            <td  align="left"  height="20">
            <?php //echo number_format($batch->getIntercept(), 3, '.', ''); 
            echo Alae\Service\Helper::getformatDecimal($batch->getIntercept()); ?>
            </td>
        </tr>	
        <tr>
            <td  align="left" height="20"   style="font-size: 13px;font-weight: bold">
                Fecha de importación:
            </td>
            <td  height="20" align="left" style="">
                <?php echo $batch->getCreatedAt(); ?>
            </td>
            <td  align="left"  height="20"   style="font-size: 13px;font-weight: bold;font-weight: bold">
                r=
            </td>
            <td  align="left"  height="20">
                <?php echo $batch->getCorrelationCoefficient(); ?>
            </td>
        </tr>
        <tr>
            <td align="left" height="20"   style="font-size: 13px;font-weight: bold">
                Resultado de la Evaluación:
            </td>
            <td  height="20" style="">
                <?php echo $batch->getValidFlag() ? "ACEPTADO" : "RECHAZADO"; ?>
            </td>
            <td  align="left"  height="20"  align="center" style="font-size: 13px;font-weight: bold">
                Motivo de Rechazo:
            </td>
            <td  align="left"  height="20">
                <?php echo htmlentities($errors); ?>
            </td>
        </tr>
        <tr>
            <td  align="left" height="20"  style="font-size: 13px;">
                Usuario:
            </td>
            <td  align="left" height="20" style="">
                <?php echo $batch->getFkUser()->getUsername(); ?>
            </td>
            <td   align="left"  height="20">
            </td>
            <td   align="left"  height="20">
            </td>
        </tr>
        <tr>
            <td  align="left" height="20" style="font-size: 13px;">
                Fecha de la Evaluación:
            </td>
            <td  align="left"  height="20" style="">
                <?php echo $batch->getValidationDate(); ?>
            </td>
            <td   align="left"  height="20">
            </td>
            <td   align="left"  height="20">
            </td>
        </tr>
        <tr>
            <td  align="left" height="20" style="font-size: 13px;">
                Variabilidad IS:
            </td>
            <td  align="left"  height="20" style="">
                <?php echo $varIs; ?>
            </td>
            <td   align="left"  height="20">
            </td>
            <td   align="left"  height="20">
            </td>
        </tr>
        <tr>
        <!-- 
            <td  align="left" height="20" style="font-size: 13px;">
                5% IS:
            </td>
            <td  align="left"  height="20" style="">
                <//?php echo $var5; ?>
            </td>
        --> 
            <td   align="left"  height="20">
            </td>
            <td   align="left"  height="20">
            </td>
        </tr>
	</table>
	
    <table border="0" cellspacing="0" cellpadding="0"  style="width:600px;background-color:#fff;padding:40px 40px 40px 40px;font: arial;margin-right:100px">

        <tr>
            <td width="200" colspan="20" align="left" height="20"  style="font-size: 13px;font-weight: bold;">
                <table>
                
                </table>
            </td>            
        </tr>

        <tr>
            <td align="center"   style="text-align:center;width:75px;color:#000; border: black 1px solid;font-size:13px;padding:4px">Sample Name</td>
            <td align="center"   style="text-align:center;width:50px;border: black 1px solid;font-size:13px;padding:4px">Analyte peak name</td>
            <td align="center"   style="text-align:center;width:50px;border: black 1px solid;font-size:13px;padding:4px">Sample Type</td>
            <td align="center"   style="text-align:center;width:110px;border: black 1px solid;;font-size:13px;padding:4px"> File name </td>
            <td align="center"   style="text-align:center;width:50px;color:#000; border: black 1px solid;font-size:13px;padding:4px">Analyte peak area</td>
            <td align="center"   style="text-align:center;width:50px;border: black 1px solid;font-size:13px;padding:4px">IS peak area</td>
            <td align="center"   style="text-align:center;width:50px;border: black 1px solid;font-size:13px;padding:4px">Area ratio</td>
            <td align="center"   style="text-align:center;width:70px;border: black 1px solid;;font-size:13px;padding:4px"> Analyte concentration</td>
            <td align="center"   style="text-align:center;width:70px;border: black 1px solid;;font-size:13px;padding:4px"> Calculated concentration</td>
            <td align="center"   style="text-align:center;width:50px;border: black 1px solid;font-size:13px;padding:4px">Dilution factor</td>
            <td align="center"   style="text-align:center;width:50px;border: black 1px solid;;font-size:13px;padding:4px"> Accuracy</td>
            <td align="center"   style="text-align:center;width:40px;border: black 1px solid;font-size:13px;padding:4px">Use record</td>
            <td align="center"   style="text-align:center;width:70px;border: black 1px solid;font-size:13px;padding:4px">Acquisition date</td>
            <td align="center"   style="text-align:center;width:80px;border: black 1px solid;font-size:13px;padding:4px">Analyte integration type</td>
            <td align="center"   style="text-align:center;width:80px;border: black 1px solid;font-size:13px;padding:4px">IS integration type</td>
            <td align="center"   style="text-align:center;width:50px;border: black 1px solid;font-size:13px;padding:4px">Record modified </td>
            <td align="center"   style="text-align:center;width:50px;border: black 1px solid;font-size:13px;padding:4px">Rejection Reason</td>
            <td align="center"   style="text-align:center;width:150px;border: black 1px solid;font-size:13px;padding:4px">Message</td>
        </tr>
        <?php echo $tr1; ?>
        <tr>
            <td colspan="20" align="right">&nbsp;</td>
        </tr>   
        <?php echo $tr2; ?>
        <tr>
            <td colspan="20" align="right">&nbsp;</td>
        </tr>
    </table>
</div>
</nobreak>