<?php
  ob_start();
?>
<page footer="page" format="432x240" orientation="L" backcolor="#FFFFFF" style="font: arial;">
    <div class="table-container" >
        <table width="600px" border="0" cellspacing="0" cellpadding="0"  style="background-color:#fff;padding:50px;">
            <tr>
                <td colspan="8">
                    <h3>RESUMEN DE LOTES DE UN ESTUDIO</h3>
                </td>
            </tr>
            <tr>
                <td  width="100px" align="left" height="30px" bgcolor="#000000" style="border: black 1px solid;color:#97C1DA;">
                    Código del estudio:
                </td>
                <td width="100px" height="30px" style="border: black 1px solid;">
                    <?php echo $study; ?>
                </td>
                <td width="100px"> &nbsp;</td>
                <td width="100px"> &nbsp;</td>
                <td  width="100px" height="30px" bgcolor="#000000" style="border: black 1px solid;color:#F1DADA;">
                    Analito
                </td>
                <td  width="100px" align="center" height="30px" style="border: black 1px solid;">
                    <?php echo $analyte; ?>
                </td>
                <td width="100px"> &nbsp;</td>
                <td width="100px"> &nbsp;</td>
            </tr>
            <tr>
                <td colspan="8">&nbsp;</td>
            </tr>
            <tr>
                <td  width="200px"  colspan="2" align="center" height="20" bgcolor="#000000" style="border: black 1px solid;color:#97C1DA;padding:4px;font-size:11px;">
                    Tabla de resultados del lote
                </td>
                <td  width="200px"  colspan="2" align="center" height="20" bgcolor="#000000" style="border: black 1px solid;color:#97C1DA;padding: 4px">
                    Evaluación 
                    <br> ( Aceptado / Rechazado )
                </td>
                <td  width="200px"  colspan="2" align="center" height="20" bgcolor="#000000" style="border: black 1px solid;color:#97C1DA;padding: 4px">
                    Motivo 
                    <br>( En caso de ser Rechazado )
                </td>
                <td  width="200px"  colspan="2" align="center" height="20" bgcolor="#000000" style="border: black 1px solid;color:#97C1DA;padding: 4px">
                    Veredicto
                </td>
            </tr>
            <?php foreach ($list as $data) : ?>
            <tr>
                <td width="200px" colspan="2"  align="left" height="20" bgcolor="#B7CCE3" style="border: black 1px solid;padding:4px;">
                    <?php echo $data['filename']; ?>
                </td>
                <td width="200px" colspan="2" align="left" height="20" bgcolor="#B7CCE3" style="border: black 1px solid;padding:4px;">
                    <?php echo $data['message']; ?>
                </td>
                <td  width="200px" colspan="2" align="left" height="20" bgcolor="#F1DADA" style="border: black 1px solid;padding:4px;">
                    <?php echo $data['error']; ?>
                </td>
                <td  width="200px" colspan="2" align="left" height="20" bgcolor="#F1DADA" style="border: black 1px solid;padding:4px;">
                    <?php echo $data['veredicto']; ?>
                </td>
            </tr>
            <?php endforeach; ?>
            <tr>
                <td align="right" width="300px" height="20" colspan="4">
                    Fecha y hora de impresión:
                </td>
                <td  align="left" width="300px" height="20"  colspan="4">
                    <?php echo date("d.m.Y H:i"); ?>
                </td>
            </tr>
        </table>
    </div>
	<page_footer>

  	</page_footer>
</page>
<?php
$content = ob_get_clean();
require_once dirname(__FILE__) . "/html2pdf/html2pdf.class.php";
try
{
    $html2pdf = new HTML2PDF('P', array(432, 240), 'en', true, 'UTF-8', array(0, 0, 0, 0));
    $html2pdf->setDefaultFont('Arial');
    $html2pdf->pdf->SetProtection(array('print'), '', '');
    $html2pdf->writeHTML($content);
    $html2pdf->Output($filename . ".pdf", 'D');
}
catch (HTML2PDF_exception $e)
{
    echo $e;
}
exit;
?>